def help():
    print('========================================HELP========================================')
    print('ADMIN')
    print('1. register - Untuk melakukan registrasi user baru')
    print('2. login - Untuk melakukan login ke dalam sistem')
    print('3. tambah_game - Untuk menambah game yang dijual pada toko')
    print('4. list_game_toko - Untuk melihat list game yang dijual pada toko')
    print('5. ubah_stok - Untuk mengubah jumlah stok game')
    print('6. cari_game - Untuk Mencari Game di Toko dari ID, Nama Game, Harga, Kategori dan Tahun Rilis')
    print('7. top_up - untuk top up saldo')
    print('8. save - untuk save segala data yang telah kita buat')
    print('\n')
    print('====================================================================================')
    print('\n')
    print('USER')
    print('1. login - Untuk melakukan login ke dalam sistem')
    print('2. membeli_game - Untuk membeli game yang berada di toko')
    print('3. melihat_game - Untuk melihat game yang sudah dimiliki')
    print('4. mencari_game_simple - Untuk mecari game berdasarkan tahun rilis dan ID')
    print('5. mencari_game_komples - Untuk Mencari Game di Toko dari ID, Nama Game, Harga, Kategori dan Tahun Rilis')
    print('6. riwayat_pembelian - untuk melihat riwayat pembelian')
    print('7. save - untuk save segala data yang telah kita buat')
    return